# Import packages

In [2]:
from growth_lib import calc_preculture_volume
import numpy as np

# Examples
## Inoculation volume from pre-culture
Our goal is to calculate the volume of an exponential-phase preculture we should use to inoculate a fresh culture to target a particular OD at a particular time the next day.

### Default current time as modeling start time
If the keyword argument 'start_time' is specified, growth_lib will use the current time.

We would like the inoculation volumes from 3 precultures with measured OD<sub>600</sub> values of 0.3435, 0.2574, and 0.4872 to target an OD<sub>600</sub> of about 0.7 at about 3:30 PM tomorrow starting with 40.0 mL fresh medium, assuming a 3.4 hr doubling time. 

Here we set these input keyword arguments: 

In [3]:
kwargs = {
    'culture_volume': 40.0, # Culture volume in mL
    'final_OD': 0.7, # Final OD value
    'desired_time': '3:30 PM', # Desired time to acheive final OD
    'measured_OD': np.array([0.3435, 0.2574, 0.4872]), # Pre-culture OD
    'doubling_time': 3.4 # Strain doubling time
}

Now we use the calc_culture_dilution() method to calculate the amount of preculture to use to inoculate the final cultures: 

In [4]:
print calc_preculture_volume(**kwargs)

[ 0.4908737   0.65507038  0.34609014]


Hence, we need to add 0.457 mL (457 $\mu$L) to one flask containing 40 mL of fresh medium and 0.610 and 0.322 mL to the others.

### User-specified modeling start time
If we set the 'start_time' keyword argument this will be used for modeling the cell growth from this time instead of the current time.

I found that, in practice, setting this for about 20 min after measurement of the preculture usually gave me just about enough time to mix about 10 flasks and place them in the incubator.

Here's an example of the same parameters from the last example but with the start time specified:

In [5]:
kwargs = {
    'start_time': '6:28 PM', # Time to start cell culture modeling
    'culture_volume': 40.0, # Culture volume in mL
    'final_OD': 0.7, # Final OD value
    'desired_time': '3:30 PM', # Desired time to acheive final OD
    'measured_OD': np.array([0.3435, 0.2574, 0.4872]), # Pre-culture OD
    'doubling_time': 3.4 # Strain doubling time
}

print calc_preculture_volume(**kwargs)

[ 0.491096    0.65536705  0.34624688]


### Detailed formula

In [13]:
kwargs = {
    'start_time': '6:28 PM', # Time to start cell culture modeling
    'culture_volume': 40.0, # Culture volume in mL
    'final_OD': 0.7, # Final OD value
    'desired_time': '3:30 PM', # Desired time to acheive final OD
    'measured_OD': np.array([0.3435, 0.2574, 0.4872]), # Pre-culture OD
    'doubling_time': 3.4, # Strain doubling time
}
print calc_preculture_volume(**kwargs)

kwargs = {
    'start_time': '6:28 PM', # Time to start cell culture modeling
    'culture_volume': 40.0, # Culture volume in mL
    'final_OD': 0.7, # Final OD value
    'desired_time': '3:30 PM', # Desired time to acheive final OD
    'measured_OD': np.array([0.3435, 0.2574, 0.4872]), # Pre-culture OD
    'doubling_time': 3.4, # Strain doubling time
    'detailed_flag': True # Use of detailed formula
}

print calc_preculture_volume(**kwargs)

[ 0.49338689  0.65842424  0.34786207]
[ 0.49954869  0.66944372  0.35091383]
